In [2]:
import numpy as np

# Generate a 3x3 random integer matrix between 2 and 10
arr = np.random.randint(low=2, high=11, size=(3, 3))

# Change data type to float
arr_float = arr * 1.0

# Convert 2D matrix into 1D array
one_d = np.reshape(arr_float, -1)

# Calculate highest and lowest values
highest = one_d.max()
lowest = one_d.min()

# Display results
print("Generated Matrix (3x3):")
print(arr)

print("\nFloat Version of Matrix:")
print(arr_float)

print("\nOne Dimensional Array:")
print(one_d)

print("\nHighest value:", highest)
print("Lowest value:", lowest)


Generated Matrix (3x3):
[[ 6 10  3]
 [ 2  3  2]
 [ 2  8  6]]

Float Version of Matrix:
[[ 6. 10.  3.]
 [ 2.  3.  2.]
 [ 2.  8.  6.]]

One Dimensional Array:
[ 6. 10.  3.  2.  3.  2.  2.  8.  6.]

Highest value: 10.0
Lowest value: 2.0
